backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - file: "src/pages/combined.md"
        label: "Combined"
        name: "combined"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "combined-page"}
      - file: "src/pages/landing.md"
        label: "Homepage"
        name: "landing"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Hero text", name: heroText, widget: text}
          - {label: "Primary CTA", name: ctaPrimary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Secondary CTA", name: ctaSecondary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
      - file: "src/pages/latest.md"
        label: "Latest project"
        name: "latest"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "latest-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Subheading, name: subheading, widget: string, required: false}
          - {label: "Body copy", name: body, widget: text}
          - {label: "Primary CTA", name: ctaPrimary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Secondary CTA", name: ctaSecondary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
      - file: "src/pages/previous-work.md"
        label: "Previous work"
        name: "previous-work"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pervious-work-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Body copy", name: body, widget: text}
          - {label: "Primary CTA", name: ctaPrimary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Secondary CTA", name: ctaSecondary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Tertiary CTA", name: ctaTertiary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Featured works", name: works, widget: list, fields: [{label: "Title", name: "title", widget: "string"}, {label: "Blurb", name: "blurb", widget: "text"}, {label: "Featured Image", name: "image", widget: image}]}
      - file: "src/pages/photography.md"
        label: "Photography"
        name: "photography"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "photography-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Body copy", name: body, widget: text}
          - {label: "Primary CTA", name: ctaPrimary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Secondary CTA", name: ctaSecondary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Tertiary CTA", name: ctaTertiary, widget: object, fields: [{label: "Button text", name: btnText, widget: string}, {label: URL, name: url, widget: string}, {label: "Title", name: title, widget: string}]}
          - {label: "Featured photos", name: photos, widget: list, fields: [{label: "Title", name: "title", widget: "string"}, {label: "Blurb", name: "blurb", widget: "text"}, {label: "Featured Image", name: "image", widget: image}]}
      - file: "src/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "photography-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Sections, name: sections, widget: list, fields: [{label: "Section title", name: sectionTitle, widget: string}, {label: "Links", name: links, widget: list, fields: [{label: "Blurb", name: "blurb", widget: text}, {label: "Button text", name: btnText, widget: string}, {label: Title, name: title, widget: string}, {label: URL, name: url, widget: string}]}]}
